compressionLevel: 0

enableGlobalCache: true

installStatePath: ../.yarn/code-install-state.gz

logFilters:
  - code: YN0007
    level: discard
  - code: YN0005
    level: discard
  - code: YN0076
    level: discard

nodeLinker: node-modules

npmRegistryServer: 'https://registry.yarnpkg.com'

plugins:
  - path: ../.yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: ../.yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: ../.yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  os:
    - current
    - linux
    - darwin

unsafeHttpWhitelist:
  - localhost

yarnPath: .yarn/releases/yarn-4.6.0.cjs
