blank_issues_enabled: false
contact_links:
  - name: View documentation 📚
    url: https://storybook.js.org/docs/
    about: Check out the official docs for answers to common questions.
  - name: Feature requests 💡
    url: https://github.com/storybookjs/storybook/discussions/new?category=ideas
    about: Suggest a feature idea for this project.
  - name: Open an RFC 🦄
    url: https://github.com/storybookjs/storybook/discussions/new?category=rfc
    about: Do you want to propose a more involved change to Storybook? Open an RFC (Request for Comments) to start a discussion.
  - name: Questions 💭
    url: https://github.com/storybookjs/storybook/discussions/new?category=help
    about: Need support with a Storybook problem? Open up a help request.
  - name: Discussions 🙌
    url: https://github.com/storybookjs/storybook/discussions
    about: Show off your Storybook or discuss the project.
  - name: Community Discord 🎉
    url: https://discord.gg/storybook
    about: Meet other community members and get contributor help.
