name: Unit tests

on:
  push:
    branches:
      - next
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Core Unit Tests, ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Set node version
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: install scripts
        run: | 
          cd scripts && yarn install

      - name: install code
        run: | 
          cd code && yarn install

      - name: compile
        run: yarn task --task compile --start-from=compile

      - name: Install Playwright Dependencies
        run: cd code && yarn exec playwright install chromium --with-deps

      - name: test
        run: yarn test
