name: Triage issues

on:
  issues:
    types: [opened, labeled]
  issue_comment:
    types: [created]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  issues: write

jobs:
  triage:
    name: Nissuer
    runs-on: ubuntu-latest
    steps:
      - uses: balazsorban44/nissuer@1.10.0
        with:
          label-comments: |
            {
              "good first issue": ".github/comments/good-first-issue.md"
            }
          reproduction-comment: ".github/comments/invalid-link.md"
          reproduction-hosts: "github.com,codesandbox.io,stackblitz.com"
          reproduction-link-section: "### Reproduction link(.*)### Reproduction steps"
          reproduction-invalid-label: "needs reproduction"
          reproduction-issue-labels: "bug,needs triage"
